openapi: 3.0.0
info:
  contact: {}
  license:
    name: ""
  title: API
  version: 1.0.0
paths:
  "": {}
  /files:
    get:
      responses:
        default:
          description: ""
  /files/{fileID}:
    delete:
      responses:
        default:
          description: ""
    get:
      responses:
        default:
          description: ""
    post:
      responses:
        default:
          description: ""
  /files/{fileID}/balance:
    post:
      responses:
        default:
          description: ""
  /files/{fileID}/batches:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBatchesResponse'
          description: List of batches
        "400":
          description: Invalid request
        default:
          description: ""
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateBatchResponse'
          description: Batch created successfully
        "400":
          description: Invalid request
        default:
          description: ""
  /files/{fileID}/batches/{batchID}:
    delete:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteBatchResponse'
          description: Batch deleted successfully
        "400":
          description: Invalid request
        default:
          description: ""
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBatchResponse'
          description: Batch details
        "400":
          description: Invalid request
        default:
          description: ""
  /files/{fileID}/flatten:
    post:
      responses:
        default:
          description: ""
  /files/{fileID}/segment:
    post:
      responses:
        default:
          description: ""
  /files/{id}/build:
    get:
      responses:
        default:
          description: ""
  /files/{id}/contents:
    get:
      responses:
        default:
          description: ""
  /files/{id}/validate:
    get:
      responses:
        default:
          description: ""
    post:
      responses:
        default:
          description: ""
  /ping:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          headers:
            Content-Type:
              description: text/plain
              schema:
                type: string
        default:
          description: ""
  /segment:
    post:
      responses:
        default:
          description: ""
components:
  schemas:
    Batch:
      description: ACH Batch object
      properties:
        batchHeader:
          description: Header information for the batch
          properties:
            companyName:
              example: Test Company
              type: string
            serviceClassCode:
              example: 200
              type: integer
          type: object
        entries:
          items:
            description: Entry detail record
            properties:
              amount:
                example: 1000
                type: integer
              transactionCode:
                example: 22
                type: integer
            type: object
          type: array
      type: object
    CreateBatchResponse:
      properties:
        error:
          description: Error message if any
          nullable: true
          type: string
        id:
          description: ID of the created batch
          type: string
      type: object
    DeleteBatchResponse:
      properties:
        error:
          description: Error message if any
          nullable: true
          type: string
      type: object
    GetBatchResponse:
      properties:
        batch:
          $ref: '#/components/schemas/Batch'
        error:
          description: Error message if any
          nullable: true
          type: string
      type: object
    GetBatchesResponse:
      properties:
        batches:
          items:
            $ref: '#/components/schemas/Batch'
          type: array
        error:
          description: Error message if any
          nullable: true
          type: string
      type: object
    ValidateOpts:
      properties:
        allowEmptyIndividualName:
          default: false
          description: Allow empty individual name
          type: boolean
        allowInvalidAmounts:
          default: false
          description: Allow invalid amounts
          type: boolean
        allowInvalidCheckDigit:
          default: false
          description: Allow invalid check digit
          type: boolean
        allowMissingFileControl:
          default: false
          description: Allow missing file control
          type: boolean
        allowMissingFileHeader:
          default: false
          description: Allow missing file header
          type: boolean
        allowSpecialCharacters:
          default: false
          description: Allow special characters
          type: boolean
        allowUnorderedBatchNumbers:
          default: false
          description: Allow unordered batch numbers
          type: boolean
        allowZeroBatches:
          default: false
          description: Allow zero batches
          type: boolean
        allowZeroEntryAmount:
          default: false
          description: Allow zero entry amount
          type: boolean
        bypassCompanyIdentificationMatch:
          default: false
          description: Bypass company identification match
          type: boolean
        bypassDestinationValidation:
          default: false
          description: Bypass destination validation
          type: boolean
        bypassOriginValidation:
          default: false
          description: Bypass origin validation
          type: boolean
        customReturnCodes:
          default: false
          description: Allow custom return codes
          type: boolean
        customTraceNumbers:
          default: false
          description: Allow custom trace numbers
          type: boolean
        preserveSpaces:
          default: false
          description: Preserve spaces in fields
          type: boolean
        requireABAOrigin:
          default: false
          description: Require ABA origin
          type: boolean
        skipAll:
          default: false
          description: Skip all validations
          type: boolean
        unequalAddendaCounts:
          default: false
          description: Allow unequal addenda counts
          type: boolean
        unequalServiceClassCode:
          default: false
          description: Allow unequal service class code
          type: boolean
      type: object
