openapi: 3.0.0
info:
  contact: {}
  license:
    name: ""
  title: API
  version: 1.0.0
paths:
  "": {}
  /files:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetFilesResponse'
          description: A list of ACH files
        default:
          description: ""
    post:
      operationId: storeFile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/File'
        description: ACH file to store
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateFileResponse'
          description: The created ACH file
        "201":
          description: ACH file stored successfully
        "400":
          description: Invalid input
        "409":
          description: File already exists
      summary: Store a new ACH file
  /files/{fileID}:
    delete:
      responses:
        default:
          description: ""
    get:
      responses:
        default:
          description: ""
    post:
      responses:
        default:
          description: ""
  /files/{fileID}/balance:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceFileResponse'
          description: Balanced file ID
        default:
          description: ""
  /files/{fileID}/batches:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchesResponse'
          description: List of batches
        "400":
          description: Invalid request
        "404":
          description: File not found
        default:
          description: ""
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResponse'
          description: Batch created successfully
        "201":
          description: Batch stored successfully
        "400":
          description: Invalid input
        "404":
          description: File not found
        "409":
          description: Batch already exists
        default:
          description: ""
  /files/{fileID}/batches/{batchID}:
    delete:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
          description: Batch deleted successfully
        "204":
          description: Batch deleted successfully
        "400":
          description: Invalid request
        "404":
          description: Batch not found
        default:
          description: ""
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResponse'
          description: Batch details
        "400":
          description: Invalid request
        "404":
          description: Batch not found
        default:
          description: ""
  /files/{fileID}/flatten:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlattenBatchesResponse'
          description: Flattened file
        default:
          description: ""
  /files/{fileID}/new:
    post:
      responses:
        default:
          description: ""
  /files/{fileID}/segment:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SegmentedFilesResponse'
          description: Segmented files
        default:
          description: ""
  /files/{id}/build:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileResponse'
          description: File built successfully
        default:
          description: ""
    post:
      operationId: buildFile
      parameters:
      - $ref: '#/components/parameters/FileID'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuildFileResponse'
          description: The built ACH file
      summary: Build a file by ID
  /files/{id}/contents:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetFileContentsResponse'
            text/plain:
              schema:
                type: string
          description: The contents of the ACH file
        default:
          description: ""
  /files/{id}/validate:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResponse'
          description: File validation result
        default:
          description: ""
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateFileResponse'
          description: Validation result
        default:
          description: ""
  /merge:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MergeResponse'
          description: Files merged successfully
        default:
          description: ""
  /ping:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
            text/plain:
              schema:
                example: PONG
                type: string
          description: Pong response
          headers:
            Content-Type:
              description: text/plain
              schema:
                type: string
        default:
          description: ""
  /segment:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SegmentResponse'
          description: File segmented successfully
        default:
          description: ""
components:
  schemas:
    ACHFile:
      properties:
        header:
          $ref: '#/components/schemas/FileHeader'
        id:
          type: string
      type: object
    BalanceFileRequest:
      properties:
        offset:
          $ref: '#/components/schemas/Offset'
      type: object
    BalanceFileResponse:
      properties:
        error:
          nullable: true
          type: string
        id:
          type: string
      type: object
    BalanceResponse:
      properties:
        balanced:
          example: true
          type: boolean
      type: object
    Batch:
      properties:
        ID:
          description: Unique identifier for the batch
          type: string
      required:
      - ID
      type: object
    BatchResponse:
      properties:
        id:
          example: batch123
          type: string
        type:
          example: PPD
          type: string
      type: object
    BatchesResponse:
      items:
        $ref: '#/components/schemas/BatchResponse'
      type: array
    BuildFileResponse:
      properties:
        error:
          nullable: true
          type: string
        file:
          $ref: '#/components/schemas/ACHFile'
      type: object
    Conditions:
      properties:
        someCondition:
          type: string
      type: object
    CreateBatchRequest:
      properties:
        batchType:
          example: PPD
          type: string
      type: object
    CreateBatchResponse:
      properties:
        error:
          description: Error message, if any.
          nullable: true
          type: string
        id:
          description: The ID of the created batch.
          type: string
      type: object
    CreateFileRequest:
      properties:
        file:
          $ref: '#/components/schemas/ACHFile'
        validateOpts:
          $ref: '#/components/schemas/ValidateOpts'
      type: object
    CreateFileResponse:
      properties:
        error:
          nullable: true
          type: string
        file:
          $ref: '#/components/schemas/ACHFile'
        id:
          type: string
      type: object
    DeleteBatchResponse:
      properties:
        error:
          description: Error message, if any.
          nullable: true
          type: string
      type: object
    DeleteFileResponse:
      properties:
        error:
          nullable: true
          type: string
      type: object
    DeleteResponse:
      properties:
        message:
          example: Resource deleted successfully
          type: string
      type: object
    File:
      properties:
        Batches:
          items:
            $ref: '#/components/schemas/Batch'
          type: array
        Header:
          properties:
            FileCreationDate:
              description: Creation date of the file in YYMMDD format
              type: string
          type: object
        ID:
          description: Unique identifier for the ACH file
          type: string
      required:
      - ID
      - Header
      type: object
    FileHeader:
      properties:
        immediateDestination:
          type: string
        immediateOrigin:
          type: string
      type: object
    FileResponse:
      properties:
        id:
          example: file123
          type: string
        name:
          example: example.ach
          type: string
      type: object
    FilesResponse:
      items:
        $ref: '#/components/schemas/FileResponse'
      type: array
    FlattenBatchesResponse:
      properties:
        error:
          nullable: true
          type: string
        file:
          $ref: '#/components/schemas/ACHFile'
        id:
          type: string
      type: object
    FlattenResponse:
      properties:
        flattened:
          example: true
          type: boolean
      type: object
    GetBatchResponse:
      properties:
        batch:
          $ref: '#/components/schemas/Batch'
        error:
          description: Error message, if any.
          nullable: true
          type: string
      type: object
    GetBatchesResponse:
      properties:
        batches:
          items:
            $ref: '#/components/schemas/Batch'
          type: array
        error:
          description: Error message, if any.
          nullable: true
          type: string
      type: object
    GetFileContentsResponse:
      properties:
        error:
          nullable: true
          type: string
      type: object
    GetFileResponse:
      properties:
        error:
          nullable: true
          type: string
        file:
          $ref: '#/components/schemas/ACHFile'
      type: object
    GetFilesResponse:
      properties:
        error:
          nullable: true
          type: string
        files:
          items:
            $ref: '#/components/schemas/ACHFile'
          type: array
      type: object
    MergeFilesRequest:
      properties:
        conditions:
          $ref: '#/components/schemas/Conditions'
        fileIDs:
          items:
            type: string
          type: array
        files:
          items:
            $ref: '#/components/schemas/ACHFile'
          type: array
      type: object
    MergeFilesResponse:
      properties:
        error:
          nullable: true
          type: string
        files:
          items:
            $ref: '#/components/schemas/ACHFile'
          type: array
      type: object
    MergeResponse:
      properties:
        merged:
          example: true
          type: boolean
      type: object
    Offset:
      properties:
        accountNumber:
          type: string
        accountType:
          type: string
        routingNumber:
          type: string
      type: object
    SegmentFileConfiguration:
      properties:
        someConfig:
          type: string
      type: object
    SegmentFileIDRequest:
      properties:
        opts:
          $ref: '#/components/schemas/SegmentFileConfiguration'
      type: object
    SegmentFileRequest:
      properties:
        file:
          $ref: '#/components/schemas/ACHFile'
        opts:
          $ref: '#/components/schemas/SegmentFileConfiguration'
        validateOpts:
          $ref: '#/components/schemas/ValidateOpts'
      type: object
    SegmentResponse:
      properties:
        segments:
          items:
            type: string
          type: array
      type: object
    SegmentedFilesResponse:
      properties:
        creditFile:
          $ref: '#/components/schemas/ACHFile'
        creditFileID:
          type: string
        debitFile:
          $ref: '#/components/schemas/ACHFile'
        debitFileID:
          type: string
        error:
          nullable: true
          type: string
      type: object
    ValidateFileResponse:
      properties:
        error:
          nullable: true
          type: string
      type: object
    ValidateOpts:
      properties:
        someOption:
          type: string
      type: object
    ValidationResponse:
      properties:
        errors:
          items:
            type: string
          type: array
        valid:
          example: true
          type: boolean
      type: object
