openapi: 3.0.0
info:
  contact: {}
  license:
    name: ""
  title: API
  version: 1.0.0
paths:
  "": {}
  /files:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetFilesResponse'
          description: A list of ACH files
        default:
          description: ""
    post:
      operationId: createFile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFileRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateFileResponse'
          description: The created file
      summary: Create a new file
  /files/{fileID}:
    delete:
      responses:
        default:
          description: ""
    get:
      responses:
        default:
          description: ""
    post:
      responses:
        default:
          description: ""
  /files/{fileID}/balance:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceFileResponse'
          description: Balanced file ID
        default:
          description: ""
  /files/{fileID}/batches:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBatchesResponse'
          description: List of batches
        "400":
          description: Invalid request
        default:
          description: ""
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateBatchResponse'
          description: Batch created successfully
        "400":
          description: Invalid request
        default:
          description: ""
  /files/{fileID}/batches/{batchID}:
    delete:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteBatchResponse'
          description: Batch deleted successfully
        "400":
          description: Invalid request
        default:
          description: ""
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBatchResponse'
          description: Batch details
        "400":
          description: Invalid request
        default:
          description: ""
  /files/{fileID}/flatten:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlattenBatchesResponse'
          description: Flattened file
        default:
          description: ""
  /files/{fileID}/segment:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SegmentedFilesResponse'
          description: Segmented files
        default:
          description: ""
  /files/{id}/build:
    get:
      responses:
        default:
          description: ""
    post:
      operationId: buildFile
      parameters:
      - $ref: '#/components/parameters/FileID'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuildFileResponse'
          description: The built file
      summary: Build a file by ID
  /files/{id}/contents:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: The file contents
        default:
          description: ""
  /files/{id}/validate:
    get:
      responses:
        default:
          description: ""
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateFileResponse'
          description: Validation result
        default:
          description: ""
  /merge:
    post:
      responses:
        default:
          description: ""
  /ping:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          headers:
            Content-Type:
              description: text/plain
              schema:
                type: string
        default:
          description: ""
  /segment:
    post:
      responses:
        default:
          description: ""
components:
  schemas:
    ACHFile:
      properties:
        header:
          $ref: '#/components/schemas/FileHeader'
        id:
          type: string
      type: object
    BalanceFileRequest:
      properties:
        offset:
          $ref: '#/components/schemas/Offset'
      type: object
    BalanceFileResponse:
      properties:
        error:
          nullable: true
          type: string
        id:
          type: string
      type: object
    Batch:
      description: ACH Batch data
      properties:
        batchHeader:
          description: Header information for the batch
          properties:
            companyName:
              description: Company name
              type: string
            serviceClassCode:
              description: Service class code
              type: integer
          type: object
        entries:
          description: Entries in the batch
          items:
            description: Entry detail
            properties:
              amount:
                description: Transaction amount
                type: integer
              transactionCode:
                description: Transaction code
                type: integer
            type: object
          type: array
      type: object
    BuildFileResponse:
      properties:
        error:
          nullable: true
          type: string
        file:
          $ref: '#/components/schemas/ACHFile'
      type: object
    Conditions:
      properties:
        someCondition:
          type: string
      type: object
    CreateBatchResponse:
      properties:
        error:
          description: Error message, if any
          nullable: true
          type: string
        id:
          description: ID of the created batch
          type: string
      type: object
    CreateFileRequest:
      properties:
        file:
          $ref: '#/components/schemas/ACHFile'
        validateOpts:
          $ref: '#/components/schemas/ValidateOpts'
      type: object
    CreateFileResponse:
      properties:
        error:
          nullable: true
          type: string
        file:
          $ref: '#/components/schemas/ACHFile'
        id:
          type: string
      type: object
    DeleteBatchResponse:
      properties:
        error:
          description: Error message, if any
          nullable: true
          type: string
      type: object
    DeleteFileResponse:
      properties:
        error:
          nullable: true
          type: string
      type: object
    FileHeader:
      properties:
        immediateDestination:
          type: string
        immediateOrigin:
          type: string
      type: object
    FlattenBatchesResponse:
      properties:
        error:
          nullable: true
          type: string
        file:
          $ref: '#/components/schemas/ACHFile'
        id:
          type: string
      type: object
    GetBatchResponse:
      properties:
        batch:
          $ref: '#/components/schemas/Batch'
        error:
          description: Error message, if any
          nullable: true
          type: string
      type: object
    GetBatchesResponse:
      properties:
        batches:
          items:
            $ref: '#/components/schemas/Batch'
          type: array
        error:
          description: Error message, if any
          nullable: true
          type: string
      type: object
    GetFileResponse:
      properties:
        error:
          nullable: true
          type: string
        file:
          $ref: '#/components/schemas/ACHFile'
      type: object
    GetFilesResponse:
      properties:
        error:
          nullable: true
          type: string
        files:
          items:
            $ref: '#/components/schemas/ACHFile'
          type: array
      type: object
    MergeFilesRequest:
      properties:
        conditions:
          $ref: '#/components/schemas/Conditions'
        fileIDs:
          items:
            type: string
          type: array
        files:
          items:
            $ref: '#/components/schemas/ACHFile'
          type: array
      type: object
    MergeFilesResponse:
      properties:
        error:
          nullable: true
          type: string
        files:
          items:
            $ref: '#/components/schemas/ACHFile'
          type: array
      type: object
    Offset:
      properties:
        accountNumber:
          type: string
        accountType:
          type: string
        routingNumber:
          type: string
      type: object
    SegmentFileConfiguration:
      properties:
        someConfig:
          type: string
      type: object
    SegmentFileIDRequest:
      properties:
        opts:
          $ref: '#/components/schemas/SegmentFileConfiguration'
      type: object
    SegmentFileRequest:
      properties:
        file:
          $ref: '#/components/schemas/ACHFile'
        opts:
          $ref: '#/components/schemas/SegmentFileConfiguration'
        validateOpts:
          $ref: '#/components/schemas/ValidateOpts'
      type: object
    SegmentedFilesResponse:
      properties:
        creditFile:
          $ref: '#/components/schemas/ACHFile'
        creditFileID:
          type: string
        debitFile:
          $ref: '#/components/schemas/ACHFile'
        debitFileID:
          type: string
        error:
          nullable: true
          type: string
      type: object
    ValidateFileResponse:
      properties:
        error:
          nullable: true
          type: string
      type: object
    ValidateOpts:
      properties:
        someOption:
          type: string
      type: object
