openapi: 3.0.0
info:
  contact: {}
  license:
    name: ""
  title: API
  version: 1.0.0
paths:
  "": {}
  /files:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FilesResponse'
          description: List of files
        default:
          description: ""
    post:
      operationId: createFile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FileHeader'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                example: file_id_123
                type: string
          description: File created successfully
        "400":
          description: Invalid input
      summary: Create a new ACH file
  /files/{fileID}:
    delete:
      responses:
        default:
          description: ""
    get:
      responses:
        default:
          description: ""
    post:
      responses:
        default:
          description: ""
  /files/{fileID}/balance:
    post:
      responses:
        default:
          description: ""
  /files/{fileID}/batches:
    get:
      responses:
        default:
          description: ""
    post:
      responses:
        default:
          description: ""
  /files/{fileID}/batches/{batchID}:
    delete:
      responses:
        default:
          description: ""
    get:
      responses:
        default:
          description: ""
  /files/{fileID}/flatten:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlattenResponse'
          description: Batches flattened successfully
        default:
          description: ""
  /files/{fileID}/segment:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SegmentResponse'
          description: File segmented successfully
        default:
          description: ""
  /files/{id}/build:
    get:
      responses:
        default:
          description: ""
  /files/{id}/contents:
    get:
      responses:
        default:
          description: ""
  /files/{id}/validate:
    get:
      responses:
        default:
          description: ""
    post:
      responses:
        default:
          description: ""
  /ping:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
            text/plain:
              schema:
                example: PONG
                type: string
          description: PONG response
          headers:
            Content-Type:
              description: text/plain
              schema:
                type: string
        default:
          description: ""
  /segment:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SegmentResponse'
          description: File segmented successfully
        default:
          description: ""
components:
  schemas:
    BalanceResponse:
      properties:
        balanced:
          example: true
          type: boolean
      type: object
    Batch:
      description: ACH Batch object
      properties:
        batchHeader:
          description: Batch header details
          properties:
            companyName:
              description: Company name
              type: string
            serviceClassCode:
              description: Service class code
              type: integer
          type: object
        entries:
          items:
            description: Entry details
            properties:
              amount:
                description: Transaction amount
                type: integer
              transactionCode:
                description: Transaction code
                type: integer
            type: object
          type: array
      type: object
    BatchResponse:
      properties:
        id:
          example: batch123
          type: string
        type:
          example: PPD
          type: string
      type: object
    BatchesResponse:
      items:
        $ref: '#/components/schemas/BatchResponse'
      type: array
    CreateBatchRequest:
      properties:
        batchType:
          example: PPD
          type: string
      type: object
    CreateBatchResponse:
      properties:
        error:
          description: Error message, if any
          nullable: true
          type: string
        id:
          description: ID of the created batch
          type: string
      type: object
    CreateFileRequest:
      properties:
        name:
          example: example.ach
          type: string
      type: object
    DeleteBatchResponse:
      properties:
        error:
          description: Error message, if any
          nullable: true
          type: string
      type: object
    File:
      properties:
        batches:
          items:
            $ref: '#/components/schemas/Batch'
          type: array
        header:
          $ref: '#/components/schemas/FileHeader'
        id:
          description: Unique identifier for the file
          type: string
      type: object
    FileHeader:
      properties:
        id:
          description: Unique identifier for the file header
          type: string
        immediateDestination:
          description: Immediate destination
          type: string
        immediateOrigin:
          description: Immediate origin
          type: string
      type: object
    FileResponse:
      properties:
        id:
          example: file123
          type: string
        name:
          example: example.ach
          type: string
      type: object
    FilesResponse:
      items:
        $ref: '#/components/schemas/FileResponse'
      type: array
    FlattenResponse:
      properties:
        flattened:
          example: true
          type: boolean
      type: object
    GetBatchResponse:
      properties:
        batch:
          $ref: '#/components/schemas/Batch'
        error:
          description: Error message, if any
          nullable: true
          type: string
      type: object
    GetBatchesResponse:
      properties:
        batches:
          items:
            $ref: '#/components/schemas/Batch'
          type: array
        error:
          description: Error message, if any
          nullable: true
          type: string
      type: object
    Offset:
      properties:
        accountNumber:
          description: Account number for offset
          type: string
        routingNumber:
          description: Routing number for offset
          type: string
      type: object
    SegmentResponse:
      properties:
        segments:
          items:
            type: string
          type: array
      type: object
    ValidationResponse:
      properties:
        errors:
          items:
            type: string
          type: array
        valid:
          example: true
          type: boolean
      type: object
