openapi: 3.0.0
info:
  contact: {}
  license:
    name: ""
  title: API
  version: 1.0.0
paths:
  "": {}
  /files:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetFilesResponse'
          description: List of ACH files
        default:
          description: ""
  /files/{fileID}:
    delete:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteFileResponse'
          description: File deleted successfully
        "204":
          description: File deleted successfully
        default:
          description: ""
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetFileResponse'
          description: ACH file details
        default:
          description: ""
    post:
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileResponse'
          description: File created successfully
        default:
          description: ""
  /files/{fileID}/balance:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceFileResponse'
          description: File balanced successfully
        default:
          description: ""
  /files/{fileID}/batches:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchesResponse'
          description: List of batches
        "400":
          description: Invalid request
        default:
          description: ""
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateBatchResponse'
          description: Batch created successfully
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResponse'
          description: Batch created successfully
        "400":
          description: Invalid request
        default:
          description: ""
  /files/{fileID}/batches/{batchID}:
    delete:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteBatchResponse'
          description: Batch deleted successfully
        "204":
          description: Batch deleted successfully
        "400":
          description: Invalid request
        default:
          description: ""
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResponse'
          description: Batch details
        "400":
          description: Invalid request
        default:
          description: ""
  /files/{fileID}/flatten:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlattenBatchesResponse'
          description: Batches flattened successfully
        default:
          description: ""
  /files/{fileID}/segment:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SegmentedFilesResponse'
          description: File segmented successfully
        default:
          description: ""
  /files/{id}/build:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileResponse'
          description: File built successfully
        default:
          description: ""
    post:
      operationId: buildFile
      parameters:
      - $ref: '#/components/parameters/FileID'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuildFileResponse'
          description: File built successfully
      summary: Build an ACH file
  /files/{id}/contents:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetFileContentsResponse'
            text/plain:
              schema:
                type: string
          description: File contents retrieved successfully
        default:
          description: ""
  /files/{id}/validate:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResponse'
          description: File validation result
        default:
          description: ""
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateFileResponse'
          description: File validated successfully
        default:
          description: ""
  /ping:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
            text/plain:
              schema:
                example: PONG
                type: string
          description: PONG
          headers:
            Content-Type:
              description: text/plain
              schema:
                type: string
        default:
          description: ""
  /segment:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileResponse'
          description: File segmented successfully
        default:
          description: ""
components:
  schemas:
    ACHFile:
      properties:
        batches:
          items:
            $ref: '#/components/schemas/Batch'
          type: array
        header:
          $ref: '#/components/schemas/FileHeader'
        id:
          description: Unique identifier for the ACH file
          type: string
      type: object
    BalanceFileRequest:
      properties:
        offset:
          $ref: '#/components/schemas/Offset'
      type: object
    BalanceFileResponse:
      properties:
        error:
          description: Error message if the operation failed
          nullable: true
          type: string
        id:
          description: Unique identifier for the balanced file
          type: string
      type: object
    Batch:
      properties:
        entries:
          items:
            $ref: '#/components/schemas/Entry'
          type: array
      type: object
    BatchResponse:
      properties:
        batch:
          $ref: '#/components/schemas/Batch'
      type: object
    BatchesResponse:
      properties:
        batches:
          items:
            $ref: '#/components/schemas/Batch'
          type: array
      type: object
    BuildFileResponse:
      properties:
        error:
          description: Error message if the operation failed
          nullable: true
          type: string
        file:
          $ref: '#/components/schemas/ACHFile'
      type: object
    CreateBatchResponse:
      properties:
        error:
          description: Error message if any
          nullable: true
          type: string
        id:
          description: ID of the created batch
          type: string
      type: object
    CreateFileRequest:
      properties:
        file:
          $ref: '#/components/schemas/ACHFile'
        validateOpts:
          $ref: '#/components/schemas/ValidateOpts'
      type: object
    CreateFileResponse:
      properties:
        error:
          description: Error message if the operation failed
          nullable: true
          type: string
        file:
          $ref: '#/components/schemas/ACHFile'
        id:
          description: Unique identifier for the created file
          type: string
      type: object
    DeleteBatchResponse:
      properties:
        error:
          description: Error message if any
          nullable: true
          type: string
      type: object
    DeleteFileResponse:
      properties:
        error:
          description: Error message if the operation failed
          nullable: true
          type: string
      type: object
    Entry:
      properties:
        amount:
          description: Amount of the transaction
          type: integer
        transactionCode:
          description: Transaction code for the entry
          type: integer
      type: object
    File:
      properties:
        created_at:
          format: date-time
          type: string
        id:
          type: string
        name:
          type: string
      type: object
    FileHeader:
      properties:
        immediateDestination:
          description: Immediate destination of the ACH file
          type: string
        immediateOrigin:
          description: Immediate origin of the ACH file
          type: string
      type: object
    FileResponse:
      properties:
        file:
          $ref: '#/components/schemas/File'
      type: object
    FilesResponse:
      properties:
        files:
          items:
            $ref: '#/components/schemas/File'
          type: array
      type: object
    FlattenBatchesResponse:
      properties:
        error:
          description: Error message if the operation failed
          nullable: true
          type: string
        file:
          $ref: '#/components/schemas/ACHFile'
        id:
          description: Unique identifier for the file with flattened batches
          type: string
      type: object
    GetBatchResponse:
      properties:
        batch:
          type: object
        error:
          description: Error message if any
          nullable: true
          type: string
      type: object
    GetBatchesResponse:
      properties:
        batches:
          items:
            type: object
          type: array
        error:
          description: Error message if any
          nullable: true
          type: string
      type: object
    GetFileContentsResponse:
      properties:
        error:
          description: Error message if the operation failed
          nullable: true
          type: string
      type: object
    GetFileResponse:
      properties:
        error:
          description: Error message if the operation failed
          nullable: true
          type: string
        file:
          $ref: '#/components/schemas/ACHFile'
      type: object
    GetFilesResponse:
      properties:
        error:
          description: Error message if the operation failed
          nullable: true
          type: string
        files:
          items:
            $ref: '#/components/schemas/ACHFile'
          type: array
      type: object
    Offset:
      properties:
        accountNumber:
          description: Account number for the offset
          type: string
        accountType:
          description: Account type for the offset
          type: string
        routingNumber:
          description: Routing number for the offset
          type: string
      type: object
    SegmentFileConfiguration:
      properties:
        someConfig:
          description: Example segment file configuration
          type: string
      type: object
    SegmentFileIDRequest:
      properties:
        opts:
          $ref: '#/components/schemas/SegmentFileConfiguration'
      type: object
    SegmentFileRequest:
      properties:
        file:
          $ref: '#/components/schemas/ACHFile'
        opts:
          $ref: '#/components/schemas/SegmentFileConfiguration'
        validateOpts:
          $ref: '#/components/schemas/ValidateOpts'
      type: object
    SegmentedFilesResponse:
      properties:
        creditFile:
          $ref: '#/components/schemas/ACHFile'
        creditFileID:
          description: Unique identifier for the credit file
          type: string
        debitFile:
          $ref: '#/components/schemas/ACHFile'
        debitFileID:
          description: Unique identifier for the debit file
          type: string
        error:
          description: Error message if the operation failed
          nullable: true
          type: string
      type: object
    ValidateFileRequest:
      properties:
        opts:
          $ref: '#/components/schemas/ValidateOpts'
      type: object
    ValidateFileResponse:
      properties:
        error:
          description: Error message if the operation failed
          nullable: true
          type: string
      type: object
    ValidateOpts:
      properties:
        someOption:
          description: Example validation option
          type: string
      type: object
    ValidationResponse:
      properties:
        errors:
          items:
            type: string
          type: array
        valid:
          type: boolean
      type: object
