openapi: 3.0.0
info:
  contact: {}
  license:
    name: ""
  title: API
  version: 1.0.0
paths:
  "": {}
  /files:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetFilesResponse'
          description: List of ACH files
        default:
          description: ""
  /files/{fileID}:
    delete:
      responses:
        default:
          description: ""
    get:
      responses:
        default:
          description: ""
    post:
      responses:
        default:
          description: ""
  /files/{fileID}/balance:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceFileResponse'
          description: File balanced successfully
        default:
          description: ""
  /files/{fileID}/batches:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchesResponse'
          description: List of batches
        default:
          description: ""
    post:
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResponse'
          description: Batch created successfully
        default:
          description: ""
  /files/{fileID}/batches/{batchID}:
    delete:
      responses:
        "204":
          description: Batch deleted successfully
        default:
          description: ""
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResponse'
          description: Batch details
        default:
          description: ""
  /files/{fileID}/flatten:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileResponse'
          description: Batches flattened successfully
        default:
          description: ""
  /files/{fileID}/segment:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SegmentedFilesResponse'
          description: File segmented successfully
        default:
          description: ""
  /files/{id}/build:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileResponse'
          description: File built successfully
        default:
          description: ""
    post:
      operationId: buildFile
      parameters:
      - $ref: '#/components/parameters/FileID'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuildFileResponse'
          description: File built successfully
      summary: Build a specific ACH file
  /files/{id}/contents:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetFileContentsResponse'
            text/plain:
              schema:
                type: string
          description: File contents retrieved successfully
        default:
          description: ""
  /files/{id}/validate:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResponse'
          description: Validation result
        default:
          description: ""
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateFileResponse'
          description: File validated successfully
        default:
          description: ""
  /ping:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
            text/plain:
              schema:
                example: PONG
                type: string
          description: PONG
          headers:
            Content-Type:
              description: text/plain
              schema:
                type: string
        default:
          description: ""
  /segment:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileResponse'
          description: File segmented successfully
        default:
          description: ""
components:
  schemas:
    BalanceFileRequest:
      properties:
        offset:
          $ref: '#/components/schemas/Offset'
      type: object
    BalanceFileResponse:
      properties:
        error:
          nullable: true
          type: string
        id:
          type: string
      type: object
    BatchResponse:
      properties:
        id:
          example: batch123
          type: string
        status:
          example: valid
          type: string
      type: object
    BatchesResponse:
      items:
        $ref: '#/components/schemas/BatchResponse'
      type: array
    BuildFileResponse:
      properties:
        error:
          nullable: true
          type: string
        file:
          $ref: '#/components/schemas/File'
      type: object
    CreateBatchRequest:
      properties:
        batch:
          example: batch content
          type: string
      type: object
    CreateFileRequest:
      properties:
        file:
          $ref: '#/components/schemas/File'
        validateOpts:
          $ref: '#/components/schemas/ValidateOpts'
      type: object
    CreateFileResponse:
      properties:
        error:
          nullable: true
          type: string
        file:
          $ref: '#/components/schemas/File'
        id:
          type: string
      type: object
    DeleteFileResponse:
      properties:
        error:
          nullable: true
          type: string
      type: object
    ErrorResponse:
      properties:
        error:
          description: Error message describing the issue.
          type: string
      type: object
    File:
      properties:
        header:
          $ref: '#/components/schemas/FileHeader'
        id:
          type: string
      type: object
    FileHeader:
      properties:
        immediateDestination:
          type: string
        immediateOrigin:
          type: string
      type: object
    FileResponse:
      properties:
        id:
          example: file123
          type: string
        status:
          example: valid
          type: string
      type: object
    FilesResponse:
      items:
        $ref: '#/components/schemas/FileResponse'
      type: array
    FlattenBatchesResponse:
      properties:
        error:
          nullable: true
          type: string
        file:
          $ref: '#/components/schemas/File'
        id:
          type: string
      type: object
    GetFileContentsResponse:
      properties:
        error:
          nullable: true
          type: string
      type: object
    GetFileResponse:
      properties:
        error:
          nullable: true
          type: string
        file:
          $ref: '#/components/schemas/File'
      type: object
    GetFilesResponse:
      properties:
        error:
          nullable: true
          type: string
        files:
          items:
            $ref: '#/components/schemas/File'
          type: array
      type: object
    Offset:
      properties:
        accountNumber:
          type: string
        accountType:
          type: string
        routingNumber:
          type: string
      type: object
    SegmentFileConfiguration:
      properties:
        someConfig:
          type: string
      type: object
    SegmentFileIDRequest:
      properties:
        opts:
          $ref: '#/components/schemas/SegmentFileConfiguration'
      type: object
    SegmentFileRequest:
      properties:
        file:
          $ref: '#/components/schemas/File'
        opts:
          $ref: '#/components/schemas/SegmentFileConfiguration'
        validateOpts:
          $ref: '#/components/schemas/ValidateOpts'
      type: object
    SegmentedFilesResponse:
      properties:
        creditFile:
          $ref: '#/components/schemas/File'
        creditFileID:
          type: string
        debitFile:
          $ref: '#/components/schemas/File'
        debitFileID:
          type: string
        error:
          nullable: true
          type: string
      type: object
    ValidateFileResponse:
      properties:
        error:
          nullable: true
          type: string
      type: object
    ValidateOpts:
      properties:
        someOption:
          type: string
      type: object
    ValidationResponse:
      properties:
        errors:
          items:
            type: string
          type: array
        valid:
          example: true
          type: boolean
      type: object
