openapi: 3.0.0
info:
  contact: {}
  license:
    name: ""
  title: API
  version: 1.0.0
paths:
  "": {}
  /files:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetFilesResponse'
          description: A list of ACH files
        default:
          description: ""
    post:
      operationId: createFile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFileRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateFileResponse'
          description: The created ACH file
      summary: Create a new ACH file
  /files/{fileID}:
    delete:
      responses:
        default:
          description: ""
    get:
      responses:
        default:
          description: ""
    post:
      responses:
        default:
          description: ""
  /files/{fileID}/balance:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceFileResponse'
          description: The balanced ACH file
        default:
          description: ""
  /files/{fileID}/batches:
    get:
      responses:
        default:
          description: ""
    post:
      responses:
        default:
          description: ""
  /files/{fileID}/batches/{batchID}:
    delete:
      responses:
        default:
          description: ""
    get:
      responses:
        default:
          description: ""
  /files/{fileID}/flatten:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlattenBatchesResponse'
          description: The flattened ACH file
        default:
          description: ""
  /files/{fileID}/segment:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SegmentedFilesResponse'
          description: The segmented ACH files
        default:
          description: ""
  /files/{id}/build:
    get:
      responses:
        default:
          description: ""
    post:
      operationId: buildFile
      parameters:
      - $ref: '#/components/parameters/FileID'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuildFileResponse'
          description: The built ACH file
      summary: Build a specific ACH file
  /files/{id}/contents:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: The contents of the ACH file
        default:
          description: ""
  /files/{id}/validate:
    get:
      responses:
        default:
          description: ""
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateFileResponse'
          description: Validation result
        default:
          description: ""
  /ping:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          headers:
            Content-Type:
              description: text/plain
              schema:
                type: string
        default:
          description: ""
  /segment:
    post:
      responses:
        default:
          description: ""
components:
  schemas:
    ACHFile:
      properties:
        header:
          $ref: '#/components/schemas/FileHeader'
        id:
          type: string
      type: object
    BalanceFileRequest:
      properties:
        offset:
          $ref: '#/components/schemas/Offset'
      type: object
    BalanceFileResponse:
      properties:
        error:
          nullable: true
          type: string
        id:
          type: string
      type: object
    BuildFileResponse:
      properties:
        error:
          nullable: true
          type: string
        file:
          $ref: '#/components/schemas/ACHFile'
      type: object
    CreateFileRequest:
      properties:
        file:
          $ref: '#/components/schemas/ACHFile'
        validateOpts:
          $ref: '#/components/schemas/ValidateOpts'
      type: object
    CreateFileResponse:
      properties:
        error:
          nullable: true
          type: string
        file:
          $ref: '#/components/schemas/ACHFile'
        id:
          type: string
      type: object
    DeleteFileResponse:
      properties:
        error:
          nullable: true
          type: string
      type: object
    FileHeader:
      properties:
        immediateDestination:
          type: string
        immediateOrigin:
          type: string
      type: object
    FlattenBatchesResponse:
      properties:
        error:
          nullable: true
          type: string
        file:
          $ref: '#/components/schemas/ACHFile'
        id:
          type: string
      type: object
    GetFileResponse:
      properties:
        error:
          nullable: true
          type: string
        file:
          $ref: '#/components/schemas/ACHFile'
      type: object
    GetFilesResponse:
      properties:
        error:
          nullable: true
          type: string
        files:
          items:
            $ref: '#/components/schemas/ACHFile'
          type: array
      type: object
    Offset:
      properties:
        accountNumber:
          type: string
        accountType:
          type: string
        routingNumber:
          type: string
      type: object
    SegmentFileConfiguration:
      properties:
        someConfig:
          type: string
      type: object
    SegmentFileIDRequest:
      properties:
        opts:
          $ref: '#/components/schemas/SegmentFileConfiguration'
      type: object
    SegmentFileRequest:
      properties:
        file:
          $ref: '#/components/schemas/ACHFile'
        opts:
          $ref: '#/components/schemas/SegmentFileConfiguration'
        validateOpts:
          $ref: '#/components/schemas/ValidateOpts'
      type: object
    SegmentedFilesResponse:
      properties:
        creditFile:
          $ref: '#/components/schemas/ACHFile'
        creditFileID:
          type: string
        debitFile:
          $ref: '#/components/schemas/ACHFile'
        debitFileID:
          type: string
        error:
          nullable: true
          type: string
      type: object
    ValidateFileResponse:
      properties:
        error:
          nullable: true
          type: string
      type: object
    ValidateOpts:
      properties:
        AllowInvalidAmounts:
          description: Allow invalid amounts.
          type: boolean
        AllowInvalidCheckDigit:
          description: Allow invalid check digit.
          type: boolean
        AllowMissingFileControl:
          description: Allow missing file control.
          type: boolean
        AllowMissingFileHeader:
          description: Allow missing file header.
          type: boolean
        AllowUnorderedBatchNumbers:
          description: Allow unordered batch numbers.
          type: boolean
        AllowZeroBatches:
          description: Allow zero batches.
          type: boolean
        AllowZeroEntryAmount:
          description: Allow zero entry amount.
          type: boolean
        BypassCompanyIdentificationMatch:
          description: Bypass company identification match.
          type: boolean
        BypassDestinationValidation:
          description: Bypass destination validation.
          type: boolean
        BypassOriginValidation:
          description: Bypass origin validation.
          type: boolean
        CustomReturnCodes:
          description: Allow custom return codes.
          type: boolean
        CustomTraceNumbers:
          description: Allow custom trace numbers.
          type: boolean
        PreserveSpaces:
          description: Preserve spaces in fields.
          type: boolean
        RequireABAOrigin:
          description: Require ABA origin validation.
          type: boolean
        SkipAll:
          description: Skip all validations.
          type: boolean
        UnequalAddendaCounts:
          description: Allow unequal addenda counts.
          type: boolean
        UnequalServiceClassCode:
          description: Allow unequal service class code.
          type: boolean
      type: object
