openapi: 3.0.0
info:
  contact: {}
  license:
    name: ""
  title: API
  version: 1.0.0
paths:
  "": {}
  /files:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetFilesResponse'
          description: A list of ACH files
        default:
          description: ""
    post:
      operationId: createFile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFileRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateFileResponse'
          description: The created ACH file
      summary: Create a new file
  /files/{fileID}:
    delete:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteFileResponse'
          description: File deleted successfully
        "204":
          description: File deleted successfully
        default:
          description: ""
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetFileResponse'
          description: The requested ACH file
        default:
          description: ""
    post:
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileResponse'
          description: File created successfully
        default:
          description: ""
  /files/{fileID}/balance:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceFileResponse'
          description: The balanced ACH file
        default:
          description: ""
  /files/{fileID}/batches:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchesResponse'
          description: List of batches
        "400":
          description: Invalid request
        default:
          description: ""
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateBatchResponse'
          description: Batch created successfully
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResponse'
          description: Batch created successfully
        "400":
          description: Invalid request
        default:
          description: ""
  /files/{fileID}/batches/{batchID}:
    delete:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteBatchResponse'
          description: Batch deleted successfully
        "204":
          description: Batch deleted successfully
        "400":
          description: Invalid request
        default:
          description: ""
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResponse'
          description: Batch details
        "400":
          description: Invalid request
        default:
          description: ""
  /files/{fileID}/flatten:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlattenBatchesResponse'
          description: The file with flattened batches
        default:
          description: ""
  /files/{fileID}/segment:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SegmentedFilesResponse'
          description: The segmented ACH files
        default:
          description: ""
  /files/{id}/build:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileResponse'
          description: File built successfully
        default:
          description: ""
    post:
      operationId: buildFile
      parameters:
      - $ref: '#/components/parameters/FileID'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BuildFileResponse'
          description: The built ACH file
      summary: Build a file by ID
  /files/{id}/contents:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
            text/plain:
              schema:
                type: string
          description: The contents of the ACH file
        default:
          description: ""
  /files/{id}/validate:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResponse'
          description: File validation result
        default:
          description: ""
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidateFileResponse'
          description: Validation result
        default:
          description: ""
  /ping:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
            text/plain:
              schema:
                example: PONG
                type: string
          description: Pong response
          headers:
            Content-Type:
              description: text/plain
              schema:
                type: string
        default:
          description: ""
  /segment:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileResponse'
          description: File segmented successfully
        default:
          description: ""
components:
  schemas:
    BalanceFileRequest:
      properties:
        offset:
          $ref: '#/components/schemas/Offset'
      type: object
    BalanceFileResponse:
      properties:
        error:
          type: string
        id:
          type: string
      type: object
    Batch:
      properties:
        created_at:
          format: date-time
          type: string
        id:
          type: string
        name:
          type: string
      type: object
    BatchResponse:
      properties:
        batch:
          $ref: '#/components/schemas/Batch'
      type: object
    BatchesResponse:
      properties:
        batches:
          items:
            $ref: '#/components/schemas/Batch'
          type: array
      type: object
    BuildFileResponse:
      properties:
        error:
          type: string
        file:
          $ref: '#/components/schemas/File'
      type: object
    CreateBatchResponse:
      properties:
        error:
          description: Error message, if any
          nullable: true
          type: string
        id:
          description: ID of the created batch
          type: string
      type: object
    CreateFileRequest:
      properties:
        file:
          $ref: '#/components/schemas/File'
        validateOpts:
          $ref: '#/components/schemas/ValidateOpts'
      type: object
    CreateFileResponse:
      properties:
        error:
          type: string
        file:
          $ref: '#/components/schemas/File'
        id:
          type: string
      type: object
    DeleteBatchResponse:
      properties:
        error:
          description: Error message, if any
          nullable: true
          type: string
      type: object
    DeleteFileResponse:
      properties:
        error:
          type: string
      type: object
    Error:
      properties:
        message:
          description: Error message.
          type: string
      type: object
    File:
      properties:
        header:
          $ref: '#/components/schemas/FileHeader'
        id:
          type: string
      type: object
    FileHeader:
      properties:
        immediateDestination:
          type: string
        immediateOrigin:
          type: string
      type: object
    FileResponse:
      properties:
        file:
          $ref: '#/components/schemas/File'
      type: object
    FilesResponse:
      properties:
        files:
          items:
            $ref: '#/components/schemas/File'
          type: array
      type: object
    FlattenBatchesResponse:
      properties:
        error:
          type: string
        file:
          $ref: '#/components/schemas/File'
        id:
          type: string
      type: object
    GetBatchResponse:
      properties:
        batch:
          $ref: '#/components/schemas/Batch'
        error:
          description: Error message, if any
          nullable: true
          type: string
      type: object
    GetBatchesResponse:
      properties:
        batches:
          items:
            $ref: '#/components/schemas/Batch'
          type: array
        error:
          description: Error message, if any
          nullable: true
          type: string
      type: object
    GetFileResponse:
      properties:
        error:
          type: string
        file:
          $ref: '#/components/schemas/File'
      type: object
    GetFilesResponse:
      properties:
        error:
          type: string
        files:
          items:
            $ref: '#/components/schemas/File'
          type: array
      type: object
    Offset:
      properties:
        accountNumber:
          type: string
        accountType:
          type: string
        routingNumber:
          type: string
      type: object
    SegmentFileConfiguration:
      properties:
        someConfig:
          type: string
      type: object
    SegmentFileIDRequest:
      properties:
        opts:
          $ref: '#/components/schemas/SegmentFileConfiguration'
      type: object
    SegmentFileRequest:
      properties:
        file:
          $ref: '#/components/schemas/File'
        opts:
          $ref: '#/components/schemas/SegmentFileConfiguration'
        validateOpts:
          $ref: '#/components/schemas/ValidateOpts'
      type: object
    SegmentedFilesResponse:
      properties:
        creditFile:
          $ref: '#/components/schemas/File'
        creditFileID:
          type: string
        debitFile:
          $ref: '#/components/schemas/File'
        debitFileID:
          type: string
        error:
          type: string
      type: object
    ValidateFileResponse:
      properties:
        error:
          type: string
      type: object
    ValidateOpts:
      properties:
        someOption:
          type: string
      type: object
    ValidationResponse:
      properties:
        errors:
          items:
            type: string
          type: array
        valid:
          type: boolean
      type: object
