openapi: 3.0.0
info:
  contact: {}
  license:
    name: ""
  title: API
  version: 1.0.0
paths:
  "": {}
  /files:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/File'
                type: array
          description: A list of ACH files
        default:
          description: ""
    post:
      operationId: createFile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FileHeader'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                description: The ID of the created file
                type: string
          description: File created successfully
        "400":
          description: Invalid input
      summary: Create a new ACH file
  /files/{fileID}:
    delete:
      responses:
        default:
          description: ""
    get:
      responses:
        default:
          description: ""
    post:
      responses:
        default:
          description: ""
  /files/{fileID}/balance:
    post:
      responses:
        default:
          description: ""
  /files/{fileID}/batches:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Batch'
                type: array
          description: A list of batches in the file
        "400":
          description: Invalid request
        default:
          description: ""
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateBatchResponse'
          description: Batch created successfully
        "201":
          content:
            application/json:
              schema:
                description: The ID of the created batch
                type: string
          description: Batch created successfully
        "400":
          description: Invalid input
        default:
          description: ""
  /files/{fileID}/batches/{batchID}:
    delete:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteBatchResponse'
          description: Batch deleted successfully
        "204":
          description: Batch deleted successfully
        "400":
          description: Invalid request
        "404":
          description: Batch not found
        default:
          description: ""
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Batch'
          description: The requested batch
        "400":
          description: Invalid request
        "404":
          description: Batch not found
        default:
          description: ""
  /files/{fileID}/flatten:
    post:
      responses:
        default:
          description: ""
  /files/{fileID}/segment:
    post:
      responses:
        default:
          description: ""
  /files/{id}/build:
    get:
      responses:
        default:
          description: ""
  /files/{id}/contents:
    get:
      responses:
        default:
          description: ""
  /files/{id}/validate:
    get:
      responses:
        default:
          description: ""
    post:
      responses:
        default:
          description: ""
  /ping:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          headers:
            Content-Type:
              description: text/plain
              schema:
                type: string
        default:
          description: ""
  /segment:
    post:
      responses:
        default:
          description: ""
components:
  schemas:
    Batch:
      properties:
        control:
          description: Batch control details
          type: object
        header:
          description: Batch header details
          type: object
        id:
          description: Unique identifier for the batch
          type: string
      type: object
    CreateBatchResponse:
      properties:
        error:
          description: Error message, if any
          nullable: true
          type: string
        id:
          description: ID of the created batch
          type: string
      type: object
    DeleteBatchResponse:
      properties:
        error:
          description: Error message, if any
          nullable: true
          type: string
      type: object
    File:
      properties:
        batches:
          items:
            $ref: '#/components/schemas/Batch'
          type: array
        header:
          $ref: '#/components/schemas/FileHeader'
        id:
          description: Unique identifier for the file
          type: string
      type: object
    FileHeader:
      properties:
        id:
          description: Unique identifier for the file header
          type: string
        immediateDestination:
          description: Immediate destination
          type: string
        immediateOrigin:
          description: Immediate origin
          type: string
      type: object
    GetBatchResponse:
      properties:
        batch:
          $ref: '#/components/schemas/Batch'
        error:
          description: Error message, if any
          nullable: true
          type: string
      type: object
    GetBatchesResponse:
      properties:
        batches:
          items:
            $ref: '#/components/schemas/Batch'
          type: array
        error:
          description: Error message, if any
          nullable: true
          type: string
      type: object
    ValidateOpts:
      properties:
        AllowEmptyIndividualName:
          description: Allow empty individual name.
          type: boolean
        AllowInvalidAmounts:
          description: Allow invalid amounts.
          type: boolean
        AllowInvalidCheckDigit:
          description: Allow invalid check digit.
          type: boolean
        AllowMissingFileControl:
          description: Allow missing file control.
          type: boolean
        AllowMissingFileHeader:
          description: Allow missing file header.
          type: boolean
        AllowSpecialCharacters:
          description: Allow special characters in fields.
          type: boolean
        AllowUnorderedBatchNumbers:
          description: Allow unordered batch numbers.
          type: boolean
        AllowZeroBatches:
          description: Allow zero batches.
          type: boolean
        AllowZeroEntryAmount:
          description: Allow zero entry amount.
          type: boolean
        BypassCompanyIdentificationMatch:
          description: Bypass company identification match.
          type: boolean
        BypassDestinationValidation:
          description: Bypass destination validation.
          type: boolean
        BypassOriginValidation:
          description: Bypass origin validation.
          type: boolean
        CustomReturnCodes:
          description: Allow custom return codes.
          type: boolean
        CustomTraceNumbers:
          description: Allow custom trace numbers.
          type: boolean
        PreserveSpaces:
          description: Preserve spaces in fields.
          type: boolean
        RequireABAOrigin:
          description: Require ABA origin validation.
          type: boolean
        SkipAll:
          description: Skip all validations.
          type: boolean
        UnequalAddendaCounts:
          description: Allow unequal addenda counts.
          type: boolean
        UnequalServiceClassCode:
          description: Allow unequal service class code.
          type: boolean
      type: object
