name: Generate OpenAPI projects

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
    contents: write

jobs:
  generate:
    name: Generate OpenAPI
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: stable
        id: go

      - name: Download EndpointElf
        run: |
          wget -O endpointelf.zip https://endpointelf-releases.nyc3.cdn.digitaloceanspaces.com/dl/EndpointElf_linux_amd64_v0.3.5.zip
          unzip endpointelf.zip

      - name: moov-io/ach
        run: |
          git clone https://github.com/moov-io/ach.git
          ./bin/endpointelf -output=projects/ach.yaml update ./ach/server/
        env:
          ENDPOINTELF_LICENSE_KEY: ${{ secrets.ENDPOINTELF_LICENSE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Save moov-io/ach
        run: |
          git config user.name "eelf-bot"
          git config user.email "bot@endpointelf.com"
          git add projects/
          git commit -m "chore: updating moov-io/ach example [skip ci]" || echo "No changes to commit"
          git push origin master
